### ISSUE TITLE
erd1eacqtcmw5kcn4f2agnxkvulsgkyu2dg6xakvult8qyr43kgjcncqtg5una

### ISSUE THREAD

**Issue by Tzbegld** [multiversx/mx-battleofyields-site#755] opened 2021-09-18 20:04 UTC
Issue / Error : Withdraw timer is displaying over 7h while it is supposed to be 6h 

![image](https://user-images.githubusercontent.com/90698247/133907159-ebaa9e68-ac90-47f4-8b68-b2d9704c513c.png)

**Comment by janniksam** [comment] 2021-09-18 21:09
Possible duplicate of #746

**Closed** 2023-02-02 10:16 UTC
